### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [1]:
import tensorflow as tf

#### Collect Fashion mnist data from tf.keras.datasets 

In [2]:
from keras.datasets import fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

Using TensorFlow backend.


#### Change train and test labels into one-hot vectors

In [5]:
y_train.shape

(60000,)

In [6]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [7]:
y_test.shape

(10000,)

In [8]:
trainY = tf.keras.utils.to_categorical(y_train)
testY = tf.keras.utils.to_categorical(y_test)

#### Build the Graph

#### Initialize model, reshape & normalize data

In [9]:
x_train=x_train.astype('float32')/255
x_test=x_test.astype('float32')/255

In [10]:
x_train=x_train.reshape((x_train.shape[0],28,28,1))
x_test=x_test.reshape((x_test.shape[0],28,28,1))

In [11]:
x_train.shape

(60000, 28, 28, 1)

In [12]:
trainY.shape

(60000, 10)

In [13]:
y_train.shape

(60000,)

In [14]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [15]:
trainY

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [17]:
from tensorflow.python.keras import Sequential
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
#model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

In [18]:
model.add(tf.keras.layers.Dense(200, activation='relu'))
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.Dropout(0.25))

### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [19]:
#Output layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))

In [20]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [21]:
model.fit(x_train,trainY,          
          validation_data=(x_test,testY),
          epochs=50,
          batch_size=32)

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Train on 60000 samples, validate on 10000 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/50
60000/60000 [==============================] - 24s 393us/sample - loss: 0.5176 - acc: 0.8132 - val_loss: 0.4321 - val_acc: 0.8376
Epoch 2/50
60000/60000 [==============================] - 19s 313us/sample - loss: 0.3856 - acc: 0.8595 - val_loss: 0.3948 - val_acc: 0.8571
Epoch 3/50
60000/60000 [==============================] - 19s 319us/sample - loss: 0.3476 - acc: 0.8745 - val_loss: 0.3562 - val_acc: 0.8717
Epoch 4/50
60000/60000 [==============================] - 20s 339us/sample - loss: 0.3233 - acc: 0.8820 - val_loss: 0.3645 - val_acc: 0.8652
Epoch 5/50
60000/60000 [==============================] - 19s 320us/sample - loss: 0.3065 - acc: 0.8872 - val_loss: 0.3783 - val_acc: 0.8591
Epoch 6/50
60000/60000 [==============================] - 21s 342us/sample - loss:

In [ ]:
print("train score: ", model.evaluate(x_train,trainY))

In [ ]:
print("test score: ", model.evaluate(x_test,testY))

In [ ]:
model.summary()